app/routes.php
<?php

Route::get( '/', 'App\Controllers\DashboardController@index' )->before( 'auth' );

Route::group( [ 'before' => 'guest' ], function() {

    //Route::get( 'register', 'App\Controllers\RegisterController@create' );
    //Route::post( 'register', 'App\Controllers\RegisterController@store' );

    Route::get( 'login', 'App\Controllers\SessionController@create' );
    Route::post( 'login', 'App\Controllers\SessionController@store' );
} );
Route::get( 'logout', 'App\Controllers\SessionController@destroy' );

Route::group( [ 'before' => 'auth' ], function() {

    Route::resource( 'user', 'App\Controllers\UserController' );
    Route::resource( 'log', 'App\Controllers\LogController', [ 'except' => [ 'create', 'store', 'edit', 'update', 'destroy' ] ] );
} );

Route::group( [ 'before' => 'auth', 'prefix' => 'catalog' ], function() {

    Route::resource( 'product', 'App\Controllers\Catalog\ProductController', [ 'except' => [ 'show' ] ] );
    Route::get('product/destroyall', 'App\Controllers\Catalog\ProductController@destroy_all');
    Route::resource( 'category', 'App\Controllers\Catalog\CategoryController', [ 'except' => [ 'show' ] ] );
    Route::get('category/destroyall', 'App\Controllers\Catalog\CategoryController@destroy_all');
} );

Route::group( [ 'before' => 'auth', 'prefix' => 'entity' ], function() {

    Route::resource( 'attribute', 'App\Controllers\Entity\AttributeController', [ 'except' => [ 'show' ] ] );

    Route::group( [ 'prefix' => 'attribute' ], function() {
        Route::resource( 'set', 'App\Controllers\Entity\Attribute\SetController', [ 'except' => [ 'show' ] ] );
    } );
} );

Route::group( [ 'before' => 'auth', 'prefix' => 'system' ], function() {

    Route::resource( 'store', 'App\Controllers\System\StoreController' );
    Route::resource( 'store_view', 'App\Controllers\System\StoreViewController', [ 'except' => [ 'index', 'show' ] ] );
    Route::resource( 'store_website', 'App\Controllers\System\StoreWebsiteController', [ 'except' => [ 'index', 'show' ] ] );

    Route::resource( 'user', 'App\Controllers\System\UserController' );

    Route::resource( 'import', 'App\Controllers\System\ImportController', [ 'except' => 'show' ] );
    Route::group( [ 'prefix' => 'import' ], function() {
        Route::resource( 'profile', 'App\Controllers\System\Import\ProfileController', [ 'except' => 'show' ] );
        Route::get( 'execute/{import_id}', 'App\Controllers\System\ImportController@addImportToCron');
        Route::get( 'getimportstep', 'App\Controllers\System\ImportController@getImportStep');
        Route::resource( 'profile/attribute/set/group', 'App\Controllers\System\Import\Profile\Attribute\Set\GroupController' );
    } );
} );

Route::group( [ 'before' => 'auth', 'prefix' => 'sales' ], function() {
    Route::resource( 'order', 'App\Controllers\Sales\OrderController' );
} );

Route::group( [ 'before' => 'auth', 'prefix' => 'ajax' ], function() {
    Route::group( [ 'prefix' => 'catalog' ], function() {
        Route::resource( 'category', 'App\Controllers\Ajax\Catalog\CategoryController', [ 'only' => 'update' ] );
        
        Route::resource( 'category/profit/percent', 'App\Controllers\Ajax\Catalog\Category\ProfitPercentController', ['only' => 'store' ] );
        Route::resource( 'product/profit/percent', 'App\Controllers\Ajax\Catalog\Product\ProfitPercentController', ['only' => 'store' ] );
    } );
} );

/* Route for import products
Route::get( '/import/execute/{import_ids_string?}', function( $import_ids_string = null ) {
    $outputStream = new \Symfony\Component\Console\Output\StreamOutput( fopen( 'php://output', 'w' ) );

    $command_arguments = [ ];
    $import_ids = explode( '-', $import_ids_string );
    foreach ( $import_ids as $import_id ) {
        if ( $import_id != '' ) {
            $command_arguments['--import_id'][] = $import_id;
        }
    }

    Artisan::call( 'import:products', $command_arguments, $outputStream );
} )->before( 'auth' );*/

// Route to send product to magento
Route::get( '/export/products/magento', function( ) {
    $outputStream = new \Symfony\Component\Console\Output\StreamOutput( fopen( 'php://output', 'w' ) );

    Artisan::call( 'export:products:magento', [ ], $outputStream );
} )->before( 'auth' );

// Route to run migrations
Route::get( '/migrations/run', function() {
    Artisan::call( 'migrate' );
} )->before( 'auth' );

app/controllers/System/Import/Profile/Attribute/Set/GroupController.php
<?php

namespace App\Controllers\System\Import\Profile\Attribute\Set;

use \View;
use \Validator;
use \Input;
use \Redirect;
use App\Controllers\BaseController;
use App\Models\Eav\Attribute\Set as EavAttributeSet;
use App\Models\System\Import\Profile\Attribute\Set\Group as ImportProfileAttributeSetGroup;
use App\Models\System\Import\Profile\Attribute\Set\Group\Sets as ImportProfileAttributeSetGroupSet;

class GroupController extends BaseController
{

    protected $layout = 'layouts.main';

    public function index()
    {
        $importProfileAttributeSetGroups = ImportProfileAttributeSetGroup::all();

        $this->layout->content = View::make( 'system.import.profile.attribute.set.group.index' )->with( [ 'import_profile_attribute_set_groups' => $importProfileAttributeSetGroups ] );
    }

    public function create()
    {
        $attribute_sets = EavAttributeSet::all();

        $this->layout->content = View::make( 'system.import.profile.attribute.set.group.create' )->with( 'attribute_sets', $attribute_sets );
    }

    public function store()
    {
        $importProfileAttributeSetGroup = new ImportProfileAttributeSetGroup();
        $importProfileAttributeSetGroup->name = Input::get( 'name' );
        $importProfileAttributeSetGroup->save();

        foreach ( Input::get( 'attribute_sets', [ ] ) as $attribute_set_id ) {
            $importProfileAttributeSetGroupSet = new ImportProfileAttributeSetGroupSet();
            $importProfileAttributeSetGroupSet->system_import_profile_attribute_set_group_id = $importProfileAttributeSetGroup->system_import_profile_attribute_set_group_id;
            $importProfileAttributeSetGroupSet->attribute_set_id = $attribute_set_id;
            $importProfileAttributeSetGroupSet->save();
        }

        return Redirect::to( 'system/import/profile/attribute/set/group' )->with( 'message', 'Import profile attrivute set <b>' . $importProfileAttributeSetGroup->name . '</b> created!' );
    }

    public function edit( $system_import_profile_attribute_set_group_id )
    {
        $import_profile_attribute_set_group = ImportProfileAttributeSetGroup::find( $system_import_profile_attribute_set_group_id );

        if ( $import_profile_attribute_set_group == null ) {
            return Redirect::to( 'system/import/profile/attribute/set/group' );
        }

        $attribute_sets = EavAttributeSet::all();

        $this->layout->content = View::make( 'system.import.profile.attribute.set.group.edit' )->with( [ 'attribute_sets' => $attribute_sets, 'import_profile_attribute_set_group' => $import_profile_attribute_set_group ] );
    }

    public function update( $system_import_profile_attribute_set_group_id )
    {
        $import_profile_attribute_set_group = ImportProfileAttributeSetGroup::find( $system_import_profile_attribute_set_group_id );

        if ( $import_profile_attribute_set_group == null ) {
            return Redirect::to( 'system/import/profile/attribute/set/group' );
        }

        $import_profile_attribute_set_group->name = Input::get( 'name' );
        $import_profile_attribute_set_group->save();

        $import_profile_attribute_set_group->sets()->delete();
        foreach ( Input::get( 'attribute_sets', [ ] ) as $attribute_set_id ) {
            $importProfileAttributeSetGroupSet = new ImportProfileAttributeSetGroupSet();
            $importProfileAttributeSetGroupSet->system_import_profile_attribute_set_group_id = $import_profile_attribute_set_group->system_import_profile_attribute_set_group_id;
            $importProfileAttributeSetGroupSet->attribute_set_id = $attribute_set_id;
            $importProfileAttributeSetGroupSet->save();
        }
        
        return Redirect::to( 'system/import/profile/attribute/set/group' )->with( 'message', 'Import profile attrivute set <b>' . $import_profile_attribute_set_group->name . '</b> updated!' );
    }

}

app/controllers/System/Import/ProfileController.php
<?php

namespace App\Controllers\System\Import;

use \View;
use \Validator;
use \Input;
use \Redirect;
use App\Controllers\BaseController;
use App\Models\Eav\Attribute as EavAttribute;
use App\Models\Eav\Attribute\Set as EavAttributeSet;
use App\Models\System\Import\Profile as SystemImportProfile;
use App\Models\System\Import\Profile\Attribute as SystemImportProfileAttribute;
use App\Models\System\Import\Profile\Attribute\Set\Group as SystemImportProfileAttributeSetGroup;

class ProfileController extends BaseController
{

    protected $layout = 'layouts.main';

    public function index()
    {

        $this->layout->content = View::make( 'system.import.profile.index' )->with( 'profiles', SystemImportProfile::all() );
    }

    public function edit( $profile_id )
    {
        $import_profile = SystemImportProfile::find( $profile_id );

        if ( $import_profile == null ) {
            return Redirect::to( 'system/import' );
        }

        $attribute_sets = [ ];
        if ( $import_profile->system_import_profile_attribute_set_group_id ) {
            foreach ( $import_profile->profile_attribute_set_group->sets->lists( 'attribute_set_id' ) as $attribute_set_id ) {
                $attribute_sets[] = EavAttributeSet::find( $attribute_set_id );
            }
        }

        $import_keys = $this->getImportKeys( $import_profile->imports->last()->path );

        $this->layout->content = View::make( 'system.import.profile.edit' )->with( [ 'import_profile' => $import_profile, 'profile_attribute_set_groups' => SystemImportProfileAttributeSetGroup::all()->lists( 'name', 'system_import_profile_attribute_set_group_id' ), 'attribute_sets' => $attribute_sets, 'import_keys' => $import_keys ] );
    }

    public function update( $profile_id )
    {
        $import_profile = SystemImportProfile::find( $profile_id );

        if ( $import_profile == null ) {
            return Redirect::to( 'system/import' );
        }

        // Change profile attribute set group and reset the attributes from profile
        if ( Input::has( 'profile_attribute_set_group' ) ) {

            // Delete old attributes
            if ( $import_profile->attribute_set_id ) {
                $import_profile->attributes()->delete();
            }

            $import_profile->system_import_profile_attribute_set_group_id = (int) Input::get( 'profile_attribute_set_group' );
            $import_profile->save();
            return Redirect::to( 'system/import/profile' );
        }

        $import_profile->name = Input::get( 'profile.name' );

        if ( count( $import_profile->isDirty() ) > 0 ) {
            $import_profile->save();
        }

        SystemImportProfileAttribute::where( 'profile_id', '=', $profile_id )->delete();
        foreach ( Input::get( 'profile.attribute', [ ] ) as $key => $attribute_id ) {
            if ( $attribute_id <= 0 ) {
                continue;
            }

            $default_value = Input::get( 'profile.default_value.' . $key );

            $profile_attribute = new SystemImportProfileAttribute();
            $profile_attribute->profile_id = $profile_id;
            $profile_attribute->attribute_id = $attribute_id;
            $profile_attribute->key = Input::get( 'profile.key.' . $key );
            $profile_attribute->default_value = $default_value;
            $profile_attribute->save();
        }

        return Redirect::to( 'system/import/profile' )->with( 'message', 'Profile updated!' );
    }

    public function destroy( $profile_id )
    {
        $import_profile = SystemImportProfile::find( $profile_id );

        if ( $import_profile == null ) {
            return Redirect::to( 'system/import/profile' )->with( 'message', 'No profile to delete.' );
        }

        if ( count( $import_profile->imports ) > 0 ) {
            return Redirect::to( 'system/import/profile' )->with( 'message', 'Profile used and can not delete.' );
        }

        $import_profile->delete();
        return Redirect::to( 'system/import/profile' )->with( 'message', 'Profile deleted with success.' );
    }

    /**
     * Get keys from multidimensional array.
     * 
     * @param string $path
     * @return array
     */
    private function getImportKeys( $path )
    {
        $contents = file_get_contents( storage_path( 'imports' ) . '/' . $path );
        $xml_obj = simplexml_load_string( $contents );

        if ( is_object( $xml_obj ) ) {
            return (array) $this->getKeys( $xml_obj );
        }
    }

    private function getKeys( $array )
    {
        foreach ( $array as $value ) {

            if ( count( $value ) <= 0 ) {
                return array_keys( (array) $array );
            }

            return $this->getKeys( $value );
        }
    }

}

app/controllers/System/ImportController.php
<?php

namespace App\Controllers\System;

use \View;
use \Validator;
use \Input;
use \Redirect;
use App\Controllers\BaseController;
use App\Models\System\Cronjobb as Cronjobb; 
use App\Models\System\Import as SystemImport;
use App\Models\System\Import\Profile as SystemImportProfile;

class ImportController extends BaseController {

    protected $layout = 'layouts.main';

    public function index() {
        $active_import = Cronjobb::where('cron_type','=','import')
                ->where('status','=','started')
                ->orwhere('cron_type','=','import')
                ->where('status','=','in progress')
                ->first();
        if ($active_import) {
            $active_import->params = json_decode($active_import->params);
        }
        $this->layout->content = View::make('system.import.index', [ 'imports' => SystemImport::all(),'active_import' =>  $active_import]);
    }

    public function create() {
        $this->layout->content = View::make('system.import.create', [ 'profiles' => SystemImportProfile::all()->lists('name', 'import_profile_id')]);
    }

    public function store() {
        if (Input::hasFile('import')) {
            $import = new SystemImport();
            $import_profile = ( Input::get('profile') == 0 ) ? new SystemImportProfile() : SystemImportProfile::find(Input::get('profile'));
            if (null == $import_profile) {
                return Redirect::to('system/import');
            }

            $file = Input::file('import');
            $filename = time() . '_' . $file->getClientOriginalName();

            $file->move(storage_path('imports'), $filename);

            $import->path = $filename;

            if (Input::has('clone_profile') && Input::get('clone_profile') == 'clone') {
                $clone_import_profile = $import_profile->replicate();
                $clone_import_profile->save();
                foreach ($import_profile->attributes as $attribute) {
                    $new_attribute = $attribute->replicate();
                    $new_attribute->profile_id = $clone_import_profile->import_profile_id;
                    $new_attribute->save();
                }
                $import_profile = $clone_import_profile;
            } else {
                if (null == $import_profile->name) {
                    $import_profile->name = $filename;
                }
                if (count($import_profile->isDirty()) > 0) {
                    $import_profile->save();
                }
            }

            $import->import_profile_id = $import_profile->import_profile_id;
            $import->save();

            return Redirect::route('system.import.profile.edit', [ 'id' => $import_profile->import_profile_id]);
        }

        return Redirect::to('system/import/create')->with('message', 'Please select a file.');
    }

    public function addImportToCron($import_id) {

        $active_import = Cronjobb::where('cron_type','=','import')
                ->where('status','=','started')
                ->orwhere('cron_type','=','import')
                ->where('status','=','in progress')
                ->first();
        if ($active_import){
            echo "Error! Import Job active!";
            die();
        }

        if ($import_id) {
            $cronjob = new Cronjobb();
            $cronjob->params = json_encode(array('import_id' => $import_id));
            $cronjob->status = 'started';
            $cronjob->cron_type = 'import';
            $cronjob->save();
        }
        
        return Redirect::to('system/import/');
    }
    
    public function getImportStep(){
        $active_import = Cronjobb::where('cron_type','=','import')
                ->where('status','=','started')
                ->orwhere('cron_type','=','import')
                ->where('status','=','in progress')
                ->first();
        return json_encode($active_import);
    }

    public function destroy($import_id) {
        $import = SystemImport::find($import_id);

        if ($import == null) {
            return Redirect::to('system/import')->with('message', 'No import to delete.');
        }

        unlink(storage_path('imports') . '/' . $import->path);

        $import->delete();
        return Redirect::to('system/import')->with('message', 'Import deleted with success.');
    }

}

app/views/system/user/create.blade.php
<div class="row left-tabbed-content">

    <?php if ( count( $errors ) > 0 ) { ?>
        <div class="container-fluid">
            <ul class="errors">
                <?php foreach ( $errors->all() as $error ) { ?>
                    <li class="alert alert-warning"><?php echo $error; ?></li>
                <?php } ?>
            </ul>
        </div>
    <?php } ?>

    <div class="col-md-2 side-col no-padding-right">
        <h3>User Information</h3>
        <ul class="tabs">
            <li>
                <a id="user_tabs_general" href="#" class="active">
                    <span>
                        General
                    </span>
                </a>
            </li>
        </ul>
    </div>
    <div class="col-md-10 main-col">
        {{ Form::open( [ 'url' => 'system/user', 'class' => 'form form-horizontal' ] ) }}

        <div class="main-col-inner">
            <div class="header">
                <div class="row">
                    <div class="col-md-6">

                    </div>
                    <div class="col-md-6">

                        <ul class="pull-right list-inline">
                            <li>
                                {{ link_to(URL::previous(), 'Back', ['class' => 'btn btn-default btn-sm']) }}
                            </li>
                            <li>
                                {{ Form::submit('Save', [ 'class'=>'btn btn-primary btn-sm' ] ) }}
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
            <div class="content">

                <div id="user_tabs_general_content">
                    <div class="header-content"><span class="fieldset-legend">General</span></div>
                    <div class="entry-content">

                        <div class="form-group form-group-sm">
                            <label for="input_firstname" class="col-sm-2 control-label">
                                First name <span class="required">*</span>
                            </label>
                            <div class="col-sm-5">
                                {{ Form::text('firstname', Input::old('firstname'), [ 'class' => 'input-block-level form-control', 'id' => 'input_firstname', 'placeholder' => 'First name' ] ) }}
                            </div>
                        </div>

                        <div class="form-group form-group-sm">
                            <label for="input_lastname" class="col-sm-2 control-label">
                                Last name <span class="required">*</span>
                            </label>
                            <div class="col-sm-5">
                                {{ Form::text('lastname', Input::old('lastname'), [ 'class' => 'input-block-level form-control', 'id' => 'input_lastname', 'placeholder' => 'Last name' ] ) }}
                            </div>
                        </div>

                        <div class="form-group form-group-sm">
                            <label for="input_email" class="col-sm-2 control-label">
                                E-mail <span class="required">*</span>
                            </label>
                            <div class="col-sm-5">
                                {{ Form::text('email', Input::old('email'), [ 'class' => 'input-block-level form-control', 'id' => 'input_email', 'placeholder' => 'E-mail' ] ) }}
                            </div>
                        </div>

                        <div class="form-group form-group-sm">
                            <label for="input_password" class="col-sm-2 control-label">
                                Password <span class="required">*</span>
                            </label>
                            <div class="col-sm-5">
                                {{ Form::password('password', [ 'class' => 'input-block-level form-control', 'id' => 'input_password', 'placeholder' => 'Password' ] ) }}
                            </div>
                        </div>

                        <div class="form-group form-group-sm">
                            <label for="input_password_confirmation" class="col-sm-2 control-label">
                                Password confirmation <span class="required">*</span>
                            </label>
                            <div class="col-sm-5">
                                {{ Form::password('password_confirmation', [ 'class' => 'input-block-level form-control', 'id' => 'input_password_confirmation', 'placeholder' => 'Password confirmation' ] ) }}
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function ( $ ) {
        $( function () {

            $( 'ul.tabs li a' ).on( 'click', function ( e ) {

                $( 'ul.tabs li a' ).removeClass( 'active' );
                $( this ).addClass( 'active' );

                var id = $( this ).attr( 'id' );
                $( '.main-col-inner .content > div' ).css( 'display', 'none' );
                $( '#' + id + '_content', '.main-col-inner .content' ).css( 'display', 'block' );

                e.preventDefault();
            } );

        } );
    })( jQuery );
</script>

app/views/system/user/edit.blade.php
<div class="row left-tabbed-content">

    <?php if ( count( $errors ) > 0 ) { ?>
        <div class="container-fluid">
            <ul class="errors">
                <?php foreach ( $errors->all() as $error ) { ?>
                    <li class="alert alert-warning"><?php echo $error; ?></li>
                <?php } ?>
            </ul>
        </div>
    <?php } ?>

    <div class="col-md-2 side-col no-padding-right">
        <h3>User Information</h3>
        <ul class="tabs">
            <li>
                <a id="user_tabs_general" href="#" class="active">
                    <span>
                        General
                    </span>
                </a>
            </li>
        </ul>
    </div>
    <div class="col-md-10 main-col">
        {{ Form::open( [ 'url' => [ 'system/user', $user->id ],'method' => 'put', 'class' => 'form form-horizontal' ] ) }}

        <div class="main-col-inner">
            <div class="header">
                <div class="row">
                    <div class="col-md-6">

                    </div>
                    <div class="col-md-6">

                        <ul class="pull-right list-inline">
                            <li>
                                {{ link_to(URL::previous(), 'Back', ['class' => 'btn btn-default btn-sm']) }}
                            </li>
                            <li>
                                {{ Form::submit('Save', [ 'class'=>'btn btn-primary btn-sm' ] ) }}
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
            <div class="content">

                <div id="user_tabs_general_content">
                    <div class="header-content"><span class="fieldset-legend">General</span></div>
                    <div class="entry-content">

                        <div class="form-group form-group-sm">
                            <label for="input_firstname" class="col-sm-2 control-label">
                                First name <span class="required">*</span>
                            </label>
                            <div class="col-sm-5">
                                {{ Form::text('firstname', $user->firstname, [ 'class' => 'input-block-level form-control', 'id' => 'input_firstname', 'placeholder' => 'First name' ] ) }}
                            </div>
                        </div>

                        <div class="form-group form-group-sm">
                            <label for="input_lastname" class="col-sm-2 control-label">
                                Last name <span class="required">*</span>
                            </label>
                            <div class="col-sm-5">
                                {{ Form::text('lastname', $user->lastname, [ 'class' => 'input-block-level form-control', 'id' => 'input_lastname', 'placeholder' => 'Last name' ] ) }}
                            </div>
                        </div>

                        <div class="form-group form-group-sm">
                            <label for="input_email" class="col-sm-2 control-label">
                                E-mail <span class="required">*</span>
                            </label>
                            <div class="col-sm-5">
                                {{ Form::text('email', $user->email, [ 'class' => 'input-block-level form-control', 'id' => 'input_email', 'placeholder' => 'E-mail' ] ) }}
                            </div>
                        </div>

                        <div class="form-group form-group-sm">
                            <label for="input_password" class="col-sm-2 control-label">
                                Password
                            </label>
                            <div class="col-sm-5">
                                {{ Form::password('password', [ 'class' => 'input-block-level form-control', 'id' => 'input_password', 'placeholder' => 'Password' ] ) }}
                            </div>
                        </div>

                        <div class="form-group form-group-sm">
                            <label for="input_password_confirmation" class="col-sm-2 control-label">
                                Password confirmation
                            </label>
                            <div class="col-sm-5">
                                {{ Form::password('password_confirmation', [ 'class' => 'input-block-level form-control', 'id' => 'input_password_confirmation', 'placeholder' => 'Password confirmation' ] ) }}
                            </div>
                        </div>

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    (function ( $ ) {
        $( function () {

            $( 'ul.tabs li a' ).on( 'click', function ( e ) {

                $( 'ul.tabs li a' ).removeClass( 'active' );
                $( this ).addClass( 'active' );

                var id = $( this ).attr( 'id' );
                $( '.main-col-inner .content > div' ).css( 'display', 'none' );
                $( '#' + id + '_content', '.main-col-inner .content' ).css( 'display', 'block' );

                e.preventDefault();
            } );

        } );
    })( jQuery );
</script>

app/views/system/user/index.blade.php
<div class="row">
    <div class="col-md-6">
        Manage stores
    </div>
    <div class="col-md-6">
        <ul class="pull-right list-inline">
            <li>
                <a href="{{ URL::route('system.user.create') }}">
                    <button type="button" class="btn btn-default btn-sm">Create user</button>
                </a>
            </li>
        </ul>
    </div>
</div>

<div class="row">
    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>

                </th>
                <th>
                    User name
                </th>
                <th>
                    E-mail
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ( $users as $user ) { ?>
                <tr>
                    <td>
                        <input type='checkbox' />
                    </td>
                    <td>
                        <?php echo $user->firstname; ?> <?php echo $user->lastname; ?>
                    </td>
                    <td>
                        <?php echo $user->email; ?>
                    </td>
                    <td>
                        <a href="{{ URL::route( 'system.user.edit', $user->id ) }}">
                            <button type="button" class="btn btn-default btn-sm">Edit</button>
                        </a>
                        {{ Form::open( [ 'route' => [ 'system.user.destroy', $user->id ], 'method' => 'delete', 'class' => 'pull-right' ] ) }}
                        <button type="submit" class="btn btn-danger btn-sm" onclick="return confirm( 'Are you sure?' )">Delete</button>
                        {{ Form::close() }}
                    </td>
                </tr>
            <?php } ?>
        </tbody>
    </table>
    <div class="text-center">
        <?php echo $users->links(); ?>
    </div>

</div>